# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.TextField(verbose_name='College/University name')),
            ],
            options={
                'verbose_name': 'All Colleges/Universities',
                'verbose_name_plural': 'All Interviews',
            },
        ),
        migrations.CreateModel(
            name='company_interviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title_designation', models.CharField(default='', max_length=1000, verbose_name='Job Title/Designation you interviewed for?')),
                ('work_experience', models.CharField(choices=[('0-1', '0-1 years'), ('1-2', '1-2 years'), ('2-3', '2-3 years'), ('3-4', '3-4 years'), ('4-5', '4-5 years'), ('5-6', '5-6 years'), ('6-7', '6-7 years'), ('7-8', '7-8 years'), ('8-9', '8-9 years'), ('9-10', '9-10 years'), ('10+', '10+ years')], max_length=500, verbose_name='Work experience at the time of this interview?')),
                ('keep_anonymous', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50, verbose_name='Would you like to keep the post anonymous?')),
                ('apear_month', models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sept', 'Sept'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=100, verbose_name='Which month did you appear for the process?')),
                ('apear_year', models.CharField(choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], max_length=100, verbose_name='Which year did you appear for the process?')),
                ('interview_prccess', models.TextField(verbose_name='Describe the process of interview?')),
                ('anything_else_review', models.TextField(verbose_name='Anything else you want to mention about the interview?')),
                ('how_did_you_get', models.CharField(choices=[('Campus Placement', 'Campus Placement'), ('Lateral hiring', 'Lateral hiring')], max_length=100, verbose_name='How did you get the interview?')),
                ('did_you_get_offer', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=100, verbose_name='Did you get the offer?')),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.all_colleges', verbose_name="What's your college name?")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.companies', verbose_name='Company Name you interviewed for?')),
            ],
            options={
                'verbose_name': 'All Interviews',
                'verbose_name_plural': 'All Interviews',
            },
        ),
        migrations.CreateModel(
            name='qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.TextField(verbose_name='Quaification')),
            ],
            options={
                'verbose_name': 'All Qualifications',
                'verbose_name_plural': 'All Qualifications',
            },
        ),
        migrations.AddField(
            model_name='company_interviews',
            name='highest_qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.qualifications', verbose_name='What is the highest qualification at the time of interview?'),
        ),
        migrations.AddField(
            model_name='company_interviews',
            name='submittedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
