# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171012_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_interviews',
            name='show_stat',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='', max_length=100, verbose_name='SHOW/HIDE'),
            preserve_default=False,
        ),
    ]
