# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_company_interviews_show_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_interviews',
            name='anything_else_review',
            field=models.TextField(default='', verbose_name='Anything else you want to mention about the interview?'),
        ),
        migrations.AlterField(
            model_name='company_interviews',
            name='apear_month',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sept', 'Sept'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], default='', max_length=100, verbose_name='Which month did you appear for the process?'),
        ),
        migrations.AlterField(
            model_name='company_interviews',
            name='apear_year',
            field=models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')], default='', max_length=100, verbose_name='Which year did you appear for the process?'),
        ),
        migrations.AlterField(
            model_name='company_interviews',
            name='college_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.all_colleges', verbose_name="What's your college name?"),
        ),
        migrations.AlterField(
            model_name='company_interviews',
            name='did_you_get_offer',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100, verbose_name='Did you get the offer?'),
        ),
        migrations.AlterField(
            model_name='company_interviews',
            name='how_did_you_get',
            field=models.CharField(choices=[('Campus Placement', 'Campus Placement'), ('Lateral hiring', 'Lateral hiring')], default='', max_length=100, verbose_name='How did you get the interview?'),
        ),
        migrations.AlterField(
            model_name='company_interviews',
            name='interview_prccess',
            field=models.TextField(default='', verbose_name='Describe the process of interview?'),
        ),
        migrations.AlterField(
            model_name='company_interviews',
            name='keep_anonymous',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='', max_length=50, verbose_name='Would you like to keep the post anonymous?'),
        ),
        migrations.AlterField(
            model_name='company_interviews',
            name='show_stat',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='hide', max_length=100, verbose_name='SHOW/HIDE'),
        ),
        migrations.AlterField(
            model_name='company_interviews',
            name='work_experience',
            field=models.CharField(choices=[('0-1', '0-1 years'), ('1-2', '1-2 years'), ('2-3', '2-3 years'), ('3-4', '3-4 years'), ('4-5', '4-5 years'), ('5-6', '5-6 years'), ('6-7', '6-7 years'), ('7-8', '7-8 years'), ('8-9', '8-9 years'), ('9-10', '9-10 years'), ('10+', '10+ years')], default='', max_length=500, verbose_name='Work experience at the time of this interview?'),
        ),
    ]
