# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20171012_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_interviews',
            name='submittedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
