# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_company_interviews_submitteddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialMediaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link', models.TextField(default='')),
                ('social_link_type', models.CharField(choices=[('icon-facebook', 'Facebook'), ('icon-twitter', 'Twitter'), ('icon-linkedin', 'Linkedin'), ('icon-google-plus', 'Google'), ('icon-youtube', 'YouTube')], max_length=240, unique=True)),
            ],
            options={
                'verbose_name': 'Social Media Links',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
