# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_socialmedialinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='alternateUserprofileurl',
            field=models.TextField(default=''),
        ),
    ]
