# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.companies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='slug_url',
            field=models.CharField(default='--', max_length=2000),
        ),
    ]
