# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170915_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
