# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reviews_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='career_griwth_oppur',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, verbose_name='Career growth & opportunities'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='company_culture',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, verbose_name='Company culture'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='compensation_benifits',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, verbose_name='Compensation & Benefits'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='job_security',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, verbose_name='Job Security'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='skill_development_learning',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, verbose_name='Skill development/learning'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='work_life_balance',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, verbose_name='Work-Life balance'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='work_statisfaction',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, verbose_name='Work Satisfaction'),
        ),
    ]
