# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170915_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=1000)),
                ('comments', models.TextField()),
            ],
        ),
    ]
