# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='working_days',
            field=models.CharField(choices=[('Monday to Saturday', 'Monday to Saturday'), ('Monday to Friday', 'Monday to Friday'), ('Alternate Saturdays off', 'Alternate Saturdays off'), ('Rotational shifts', 'Rotational shifts')], max_length=200, verbose_name='Working Days'),
        ),
    ]
