# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_reviews_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='facebook_link',
            field=models.TextField(default='http://facebook.com'),
        ),
        migrations.AddField(
            model_name='companies',
            name='google_plus_link',
            field=models.TextField(default='http://google.com'),
        ),
        migrations.AddField(
            model_name='companies',
            name='linkedin_link',
            field=models.TextField(default='http://linkedin.com'),
        ),
        migrations.AddField(
            model_name='companies',
            name='twitter_link',
            field=models.TextField(default='http://twitter.com'),
        ),
    ]
